<a href="https://colab.research.google.com/github/Nikhil5566/EDA-Prostate-cancer-dataset-/blob/main/animedataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
FileName = './anime_dataset.csv'

# New section

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(FileName)
df.head(5)

<ipython-input-24-18bdfc8bbc73>:1: DtypeWarning: Columns (0,3,7,8,9,10,13,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(FileName)

,Anime_ID,Title,Genre,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,"Fantasy, Horror, Action",36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2018-12-12,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,"Romance, Action",58,ONA,Ufotable,Game,7.83,5484,450384,41331,2024-08-31,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...
2,3,Guy explain human everybody,"Drama, Comedy",2,ONA,Wit Studio,Game,6.67,3840,871129,9746,2015-08-13,2025-12-22,46,Saturday,"Bandai Namco, Aniplex","Funimation, Crunchyroll",7.85,18212,Simple attack radio mission enjoy know. Find e...
3,4,Himself forward recent,"Supernatural, Drama",92,OVA,Wit Studio,Game,8.34,3144,515087,13067,2017-07-18,2029-04-14,57,Thursday,"Kadokawa, Bandai Namco",Netflix,8.79,8818,Second shoulder pattern. Among reality central...
4,5,Out increase choose,"Adventure, Drama, Supernatural",41,TV,A-1 Pictures,Webtoon,6.45,3857,622931,17013,2016-03-24,2026-12-15,52,Sunday,"TV Tokyo, Kodansha","Viz Media, Funimation",6.44,10012,During none here. Decision chair point positio...

In [ ]:
# Displaying the column:
print(df.columns)

Index(['Anime_ID', 'Title', 'Genre', 'Episodes', 'Type', 'Studio', 'Source',
       'Rating', 'Popularity', 'Members', 'Favorites', 'Airing_Start',
       'Airing_End', 'Duration', 'Broadcast_Day', 'Producers', 'Licensors',
       'Score', 'Rank', 'Synopsis'],
      dtype='object')

In [ ]:
# Information about the dataset:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361019 entries, 0 to 361018
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Anime_ID       361019 non-null  object
 1   Title          360985 non-null  object
 2   Genre          361019 non-null  object
 3   Episodes       361019 non-null  object
 4   Type           361019 non-null  object
 5   Studio         361019 non-null  object
 6   Source         361019 non-null  object
 7   Rating         361019 non-null  object
 8   Popularity     361019 non-null  object
 9   Members        361019 non-null  object
 10  Favorites      361019 non-null  object
 11  Airing_Start   361019 non-null  object
 12  Airing_End     361019 non-null  object
 13  Duration       361019 non-null  object
 14  Broadcast_Day  361019 non-null  object
 15  Producers      361019 non-null  object
 16  Licensors      361019 non-null  object
 17  Score          361019 non-null  object
 18  Rank           361019 non-null  object
 19  Synopsis       361019 non-null  object
dtypes: object(20)
memory usage: 55.1+ MB

In [ ]:
# Describing the dataset:
print(df.describe())

        Anime_ID   Title   Genre  Episodes    Type  Studio        Source  \
count     361019  360985  361019    361019  361019  361019        361019
unique    332768  267523    1112       199       6      11             7
top        23642    Hair  Sci-Fi        33     ONA   MAPPA  Visual Novel
freq           2      54   11044      3479   72499   36497         60365

           Rating  Popularity  Members  Favorites Airing_Start  Airing_End  \
count   361019.00      361019   361019     361019       361019      361019
unique    1003.00       19637   291164      73880         3654        1827
top          6.86         378   127473       4073   2021-05-11  2028-10-18
freq       739.00          60        7         20          156         250

        Duration Broadcast_Day Producers Licensors     Score    Rank  \
count     361019        361019    361019    361019  361019.0  361019
unique       101             8        37        26    1003.0   36028
top           26      Thursday  TV Tokyo   Netflix       9.0   10426
freq        6852         51957     30285     36308     739.0      39

                                                 Synopsis
count                                              361019
unique                                             300001
top     Order per far even something of never. Natural...
freq                                                    2

In [ ]:
# Displaying the number of rows and columns:
print(df.shape)

(361019, 20)

In [ ]:
# Displaying the type of data:
print(df.dtypes)

Anime_ID         object
Title            object
Genre            object
Episodes         object
Type             object
Studio           object
Source           object
Rating           object
Popularity       object
Members          object
Favorites        object
Airing_Start     object
Airing_End       object
Duration         object
Broadcast_Day    object
Producers        object
Licensors        object
Score            object
Rank             object
Synopsis         object
dtype: object

In [ ]:
# Checking for the missing values:
missingVales = df.isnull().sum()
print(missingVales)

# Checking for the duplicate values:
duplicateValues = df.duplicated().sum()
print(duplicateValues)

Anime_ID          0
Title            34
Genre             0
Episodes          0
Type              0
Studio            0
Source            0
Rating            0
Popularity        0
Members           0
Favorites         0
Airing_Start      0
Airing_End        0
Duration          0
Broadcast_Day     0
Producers         0
Licensors         0
Score             0
Rank              0
Synopsis          0
dtype: int64
28251

In [ ]:
#  Removing too many missing column values
# Check if the column name exists before dropping
if 'Title' in df.columns:
    df_cleaning = df.drop(columns=['Title'])
else:
    print("Column 'Title' not found in the DataFrame.")
    df_cleaning = df.copy()  # Create a copy without dropping

df_cleaning.isnull().sum()

Column 'Title' not found in the DataFrame.

Anime_ID         0
Genre            0
Episodes         0
Type             0
Studio           0
Source           0
Rating           0
Popularity       0
Members          0
Favorites        0
Airing_Start     0
Airing_End       0
Duration         0
Broadcast_Day    0
Producers        0
Licensors        0
Score            0
Rank             0
Synopsis         0
dtype: int64